
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory
    username: root
    password: inventorypw

  kafka:
    bootstrapAddress: localhost:19092

my:
  bootstrap-servers: localhost:19092
  outbound-success-event-channel: payment
  outbound-failure-event-channel: order


server:
  port: 8081
